title: "METAINFO"
description: ""
lang: "ru_RU"

twitter:
  username: "metadatafdn"
  card: "summary"
social:
  name: "METADATA Foundation"
  links:
    - https://twitter.com/metadatafdn
    - https://vk.com/metadatafdn

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sass_dir: assets/css/

author:
  name: "Kitsune Solar"
  email: "kitsune.solar@gmail.com"
  github: "KitsuneSolar"
  twitter: "KitsuneSolar"
