fonts:
  - https://fonts.googleapis.com/css?family=Roboto+Condensed:400,400i,700,700i&amp;subset=cyrillic
  - https://fonts.googleapis.com/css?family=Roboto:400,400i,700,700i&amp;subset=cyrillic
  - https://fonts.googleapis.com/css?family=Fira+Mono:400,700&amp;subset=cyrillic
  - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css

styles:
  - https://cdn.jsdelivr.net/npm/bulma/css/bulma.min.css
  - https://cdn-storage.github.io/styles/theme/theme.css

scripts:
  - https://cdn.jsdelivr.net/npm/jquery
  - https://cdn.jsdelivr.net/npm/clipboard
  - https://cdn-storage.github.io/scripts/api/fetch.cache.min.js
  - https://cdn-storage.github.io/scripts/github/github.api.min.js
  - https://cdn-storage.github.io/scripts/github/github.get.org.repos.min.js
  - https://cdn-storage.github.io/scripts/bulma/bulma.min.js
  - https://cdn-storage.github.io/scripts/theme/theme.min.js

meta:
  title: ""
  keywords: ""
  copyright: "METADATA Foundation"
  theme-color: "#f3f6f9"

html:
  copyright: "<span class='meta-cr'><i class='fas fa-code'></i> with <i class='fas fa-heart' style='color: #fe6e3a;'></i> by <a title='Web Application Development Company' href='https://metadata.foundation/'><strong>METADATA</strong></a></span>"

cdn:
  url: "https://cdn-storage.github.io"
